### ISSUE TITLE
Need gui.pick_node for GUI that is set to adjust reference disabled

### ISSUE THREAD

**Issue by subsoap** [britzl/lowrezjam-template#13]
People may want to have GUI which aligns to their world/render area/is and does not float around, like the hud currently is in this example. Then to be able to click on these and have nodes be able to be accurately picked with guil.pick_node along with a helper function like rendercam does.

Need this feature in this example.

**Comment by britzl** [comment]
Fixed by https://github.com/britzl/lowrezjam-template/pull/14
