### ISSUE TITLE
the mesh '/lowrezjam/models/quad.dae' can't be found

### ISSUE THREAD

**Issue by rduke1982** [britzl/lowrezjam-template#9]
<img width="473" alt="image" src="https://user-images.githubusercontent.com/4392457/183278777-2815c08d-fbb6-4752-a9ed-e52aff1ed5e7.png">

When trying Project > Bundle > Android, this error occurs. I think it's because the wrong quad file is selected (or the ones selected are not provided).

**Comment by britzl** [comment]
Thanks for pointing it out!
